#input 8 numbers and print all unique numbers
s = set()
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
n = int(input("Enter the first number: "))
s.add(n)
print(s)